import "@mantine/core/styles.css";
import localFont from "next/font/local";
import "./globals.css";
import Footer from "@/components/Footer";
import Header from "@/components/Header";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

import { Vazirmatn } from "next/font/google";
const vazirmatn = Vazirmatn({
  subsets: ["latin"],
  variable: "--vazirmatn-font",
  weight: ["400", "700"],
});

export const metadata = {
  title: {
    default: "الفوز بالجنه",
    template: "%s | الفوز بالجنه",
  },
  description: "Generated by nada",
  keywords: ["app", "singleapp"],
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${vazirmatn.variable} ${geistSans.variable}`}>
      <body className="antialiased">
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
